// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner"; // ← これを追加

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Avatar App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
        {children}
        <Toaster /> {/* ← これをbodyの中（最後）に追加 */}
      </body>
    </html>
  );
}